[project]
name = "flavor manifold"
version = "0.1.0"
description = "an end to end data-driven flavor manipulation pipeline"
dependencies = [
    "tqdm>=4.67.3",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
