[project]
name = "my-project"
version = "0.1.0"
description = "A short description of my project"
dependencies = [
    "tqdm>=4.67.3",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
